#ifndef DUNEHDWEBPLUGIN_GLOBAL_H
#define DUNEHDWEBPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DUNEAPI_LIBRARY)
#  define DUNEAPISHARED_EXPORT Q_DECL_EXPORT
#else
#  define DUNEAPISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DUNEHDWEBPLUGIN_GLOBAL_H
